# Default values for step_starter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: ms-object-api

image:
  repository: ghcr.io/alercebroker/multisruvey_object_api
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets:
  - name: "image-pull-access"
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 8000

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
          - matchExpressions:
            - key: eks.amazonaws.com/nodegroup
              operator: In
              ## Override this value with the NodeGroup tag accordingly
              values: []

nameOverride: ""

ingress:
  certificateArn: ""
  host: ""
  k8sGroupName: ""
  k8sTags: ""
  path: "" # path without end /


imageCredentials:
  registry: ""
  username: ""
  password: ""
  email: ""

serviceCommand: ["poetry", "run", "object"]

configmap:
  env: ""
  apiUrl: ""
  port: ""
  root_path: ""
  log_level: ""

secrets:
  psql:
    user: ""
    password: ""
    database: ""
    host: ""
    port: ""
