version: "3"
services:
  #postgres database for alerts
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
  #mongodb database for alerts
  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
  # api service
  alerts_api: 
    build:
      context: ../../../
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8082:8082
