apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "catshtm-api.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  catalogs: '{{ .Values.configmap.catalogs }}'
  data-path: '{{ .Values.configmap.data_path }}'
  root-path: '{{ .Values.configmap.root_path }}'
