apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "catshtm-api.fullname" . }}
  labels:
    {{- include "catshtm-api.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: {{ .Values.volume.storage }}
  csi:
    driver: ebs.csi.aws.com
    fsType: ext4
    volumeHandle: {{ .Values.volume.handle }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.ebs.csi.aws.com/zone
              operator: In
              values:
                - {{ .Values.volume.zone }}
