apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "catshtm-api.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: ""
  volumeName: {{ include "catshtm-api.fullname" . }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.storage }}
