apiVersion: v1
kind: Service
metadata:
  name: {{ include "catshtm-api.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "catshtm-api.labels" . | nindent 4 }}
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /
    prometheus.io/scrape: "true"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "catshtm-api.selectorLabels" . | nindent 4 }}
