---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Values.namespace }}
data:
  port: '{{ .Values.configmap.port }}'
  api-url: '{{ .Values.configmap.apiUrl }}'
  service:  '{{ .Values.configmap.service }}'
---
apiVersion: v1
metadata:
  name: {{ include "service.name" . }}-nginx-conf
  namespace: {{ .Values.namespace }}
data:
  default.conf: '{{ .Values.configmap.nginxConf }}'
  default.conf: |
    server {
      listen 80;

      location {{ .Values.ingress.path }}/ {
        proxy_pass http://localhost:8000/;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Prefix {{ .Values.ingress.path }}/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
      }

      location {{ .Values.ingress.path }} {
        proxy_pass http://localhost:8000/;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Prefix {{ .Values.ingress.path }};
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
      }

      location / {
        proxy_pass http://localhost:8000/;
      }

      location /metrics {
        proxy_pass http://localhost:8000/metrics;
      }
    }
kind: ConfigMap
