---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lightcurve.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  port: '{{ .Values.configmap.port }}'
---
apiVersion: v1
metadata:
  name: lightcurve-nginx-conf
  namespace: {{ .Values.namespace }}
data:
  default.conf: |
    server {
      listen 80;

      location /v2/lightcurve/ {
        proxy_pass http://localhost:8000/;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Prefix /v2/lightcurve;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Host $http_host;
      }
    }
kind: ConfigMap