apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lightcurve.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "lightcurve.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "lightcurve.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "lightcurve.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "lightcurve.fullname" . }}
                  key: port
            - name: PSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: database-auth
                  key: sql-host
            - name: PSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-auth
                  key: sql-database
            - name: PSQL_USER
              valueFrom:
                secretKeyRef:
                  name: database-auth
                  key: sql-user
            - name: PSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-auth
                  key: sql-password
            - name: PSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: database-auth
                  key: sql-port
            - name: MONGO_HOST
              valueFrom:
                secretKeyRef:
                  name: database-auth
                  key: mongo-host
            - name: MONGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: database-auth
                  key: mongo-database
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: database-auth
                  key: mongo-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: database-auth
                  key: mongo-password
            - name: MONGO_PORT
              valueFrom:
                secretKeyRef:
                  name: database-auth
                  key: mongo-port
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-key
                  key: secret-key
        - name: nginx-sidecar
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          resources:
            requests:
              memory: 64M
              cpu: 50m  
      volumes:
        - name: nginx-conf
          configMap:
            name: lightcurve-nginx-conf
            items:
              - key: "default.conf"
                path: "default.conf"
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
