---
apiVersion: v1
kind: Secret
metadata:
  name: database-auth
  namespace: {{ .Values.namespace }}
stringData:
  sql-host: {{ .Values.secrets.sql.host }}
  sql-database: {{ .Values.secrets.sql.database }}
  sql-user: {{ .Values.secrets.sql.user }}
  sql-password: {{ .Values.secrets.sql.password }}
  sql-port: '{{ .Values.secrets.sql.port }}'
  mongo-host: {{ .Values.secrets.mongo.host }}
  mongo-database: {{ .Values.secrets.mongo.database }}
  mongo-user: {{ .Values.secrets.mongo.user }}
  mongo-password: {{ .Values.secrets.mongo.password }}
  mongo-port: '{{ .Values.secrets.mongo.port }}'
  mongo-auth-source: {{ .Values.secrets.mongo.authSource }}
---
apiVersion: v1
kind: Secret
metadata:
  name: secret-key
  namespace: {{ .Values.namespace }}
stringData:
  secret-key: {{ .Values.secrets.secretKey }}
