language: python

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install coverage

script:
  - coverage run --source api -m pytest tests

after_success: bash <(curl -s https://codecov.io/bash)