---
PROFILE_CONFIG:
  enabled: false
  storage:
    engine: sqlite
  basicAuth:
    enabled: true
    username: admin
    password: admin
  ignore:
    - "^/static/.*"
DATABASE:
  MONGO:
    HOST: ${MONGO_HOST}
    USERNAME: ${MONGO_USER}
    PASSWORD: ${MONGO_PASSWORD}
    PORT: ${MONGO_PORT}
    DATABASE: ${MONGO_DATABASE}
    AUTH_SOURCE: ${MONGO_AUTH_SOURCE}
RALIDATOR_SETTINGS:
  SECRET_KEY: ${SECRET_KEY}
  ON_AUTH_ERROR_DEFAULT_USER: true
RESTX_MASK_SWAGGER: false
