FROM python:3.8-slim

RUN apt update && apt install -y git

ADD examples/examples/infrastructure/examples_requirements.txt /app/
WORKDIR /app

RUN pip install --upgrade pip
RUN pip install -r examples_requirements.txt

COPY . /app
CMD ["/bin/bash","examples/examples/infrastructure/scripts/entrypoint.sh"]
