version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - APP_WORKERS=1
      - APP_THREADS=1
      - prometheus_multiproc_dir=/tmp
      - LOG_LEVEL=info
    ports:
    - 5000:5000
