FROM python:3.8-slim
ARG GITHUB_TOKEN

RUN apt update && apt install -y git
RUN git config --global url."https://${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"

ADD examples/examples/infrastructure/examples_requirements.txt /app/
WORKDIR /app

RUN pip install --upgrade pip
RUN pip install -r examples_requirements.txt

COPY . /app
CMD ["/bin/bash","examples/examples/infrastructure/scripts/entrypoint.sh"]
