version: "3"
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=database
    ports:
      - 27017:27017

  lightcurve:
    build:
      context: ../
      dockerfile: lightcurve/Dockerfile
    ports:
      - 8001:8000
    env_file:
      - filled_variables.env
    environment:
      SERVICE: api
      API_URL: http://localhost:8001

  object:
    build:
      context: ../
      dockerfile: lightcurve/Dockerfile
    ports:
      - 8002:8000
    env_file:
      - filled_variables.env
    environment:
      SERVICE: object_api
      API_URL: http://localhost:8002

  magstats:
    build:
      context: ../
      dockerfile: lightcurve/Dockerfile
    ports:
      - 8003:8000
    env_file:
      - filled_variables.env
    environment:
      SERVICE: magstats_api
      API_URL: http://localhost:8003

  probability:
    build:
      context: ../
      dockerfile: lightcurve/Dockerfile
    ports:
      - 8004:8000
    env_file:
      - filled_variables.env
    environment:
      SERVICE: probability_api
      API_URL: http://localhost:8004
