[tool.poetry]
name = "lightcurve"
version = "0.1.0"
description = "Get lightcurve of objects from ZTF and ATLAS surveys"
authors = ["Diego Rodriguez Mancini"]
readme = "README.md"
packages = [{include = "core", from = "src"}, {include = "api", from = "src"}, {include = "database", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
SQLAlchemy = "^2.0.19"
pymongo = "^4.4.1"
returns = "^0.21.0"
psycopg2-binary = "^2.9.6"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.0"
pytest-docker = "^2.0.0"
httpx = "^0.24.1"
pytest-cov = "^4.1.0"

[tool.poetry.group.dev.dependencies]
fastapi = "^0.100.0"
uvicorn = {extras = ["standard"], version = "^0.23.1"}

[tool.poetry.group.profiling.dependencies]
memray = "^1.8.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
