---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "astroobject.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  port: '{{ .Values.configmap.port }}'
  prefix: {{ .Values.configmap.prefix }}
---
apiVersion: v1
metadata:
  name: astroobject-nginx-conf
  namespace: web-services
data:
  default.conf: |
    server {
      listen 80;

      location /alerts/v2 {
        proxy_pass http://localhost:8000/;
        proxy_redirect off;
        proxy_set_header X-Forwarded-Prefix /alerts/v2;
      }
    }
kind: ConfigMap