apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "astroobject.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  port: '{{ .Values.configmap.port }}'
  prefix: {{ .Values.configmap.prefix }}