apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "service.name" . }}-write"
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
      matchLabels:
        {{- include "service.selectorLabels" . | nindent 6}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "service.name" . }}-read"
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes: 
  - ReadOnlyMany
  resources:
    requests:
      storage: 2Gi
  selector:
      matchLabels:
        {{- include "service.selectorLabels" . | nindent 6}}
