apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ include "service.name" . }}"
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: gp2
  volumeMode: Filesystem
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  selector:
      matchLabels:
        {{- include "service.selectorLabels" . | nindent 8}}
