apiVersion: v1
kind: Secret
metadata:
  name: tns-bot
  namespace: {{ .Values.namespace }}
stringData:
  id: "{{ .Values.secrets.tns_bot_id }}"
  name: "{{ .Values.secrets.tns_bot_name }}"
  api-key: "{{ .Values.secrets.tns_bot_api_key }}"
