apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "<CHARTNAME>.fullname" . }}
  namespace: {{ .Values.namespace }}
data:
  consumer-topics: {{ .Values.configmap.consumerTopics }}
  internal-server: {{ .Values.configmap.internalServer }}
  scribe-topic: {{ .Values.configmap.scribeTopic }}
  producer-topic: {{ .Values.configmap.producerTopic }}
  metrics-topic: {{ .Values.configmap.metricsTopic }}