apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations: {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels: {{- include "service.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets: {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: {{- toYaml .Values.serviceCommand | nindent 12}}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ include "service.name" . }}
                  key: env
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "service.name" . }}
                  key: api-url
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: {{ include "service.name" . }}
                  key: port
            - name: ROOT_PATH
              valueFrom:
                configMapKeyRef:
                  name: {{ include "service.name" . }}
                  key: root-path
            - name: LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: {{ include "service.name" . }}
                  key: log-level
            - name: PSQL_USER
              valueFrom:
                secretKeyRef:
                  name: psql
                  key: user
            - name: PSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql
                  key: password
            - name: PSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: psql
                  key: database
            - name: PSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: psql
                  key: host
            - name: PSQL_PORT
              valueFrom:
                secretKeyRef:
                  name: psql
                  key: port
        - name: nginx-sidecar
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf
          resources:
            requests:
              memory: 64M
              cpu: 50m  
      volumes:
        - name: nginx-conf
          configMap:
            name: {{ include "service.name" . }}-nginx-conf
            items:
              - key: "default.conf"
                path: "default.conf"
      affinity: {{- toYaml .Values.affinity | nindent 8 }}
