apiVersion: v1
kind: Secret
metadata:
  name: psql
  namespace: {{ .Values.namespace }}
stringData:
  user: {{ .Values.secrets.psql.user }}
  password: {{ .Values.secrets.psql.password }}
  database: {{ .Values.secrets.psql.database }}
  host: {{ .Values.secrets.psql.host }}
  port: {{ .Values.secrets.psql.port }}
---
apiVersion: v1
kind: Secret
metadata:
  name: image-pull-access
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
