apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ws-api.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ include "ws-api.name" . }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app: {{ include "ws-api.name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: {{ .Values.strategy.maxSurge }}
      maxUnavailable: {{ .Values.strategy.maxUnavailable }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        app: {{ include "ws-api.name" . }}
    spec:
      {{- if .Values.nodegroup }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nodegroup
                operator: In
                values:
                - {{ .Values.nodegroup }}
      {{- end }}
      containers:
      - name: {{ include "ws-api.name" . }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.containerPort }}
          protocol: TCP
        {{- with .Values.env }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- if .Values.nginx.enabled }}
      - name: nginx-sidecar
        image: {{ .Values.nginx.image }}
        imagePullPolicy: {{ .Values.nginx.pullPolicy }}
        ports:
        - containerPort: {{ .Values.nginx.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.nginx.resources | nindent 10 }}
        volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf
          name: nginx-conf
          subPath: default.conf
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range . }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      restartPolicy: Always
      {{- if .Values.nginx.enabled }}
      volumes:
      - name: nginx-conf
        configMap:
          name: {{ include "ws-api.nginxConfigMapName" . }}
          items:
          - key: default.conf
            path: default.conf
      {{- end }}
