{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
{{- if $secret.immutable }}
immutable: true
{{- end }}
type: {{ $secret.type | default "Opaque" }}
data:
{{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
