# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_server/xmatch.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18grpc_server/xmatch.proto\"\x86\x01\n\x11\x43onesearchRequest\x12\n\n\x02ra\x18\x01 \x01(\x02\x12\x0b\n\x03\x64\x65\x63\x18\x02 \x01(\x02\x12\x0e\n\x06radius\x18\x03 \x01(\x02\x12\x14\n\x07\x63\x61talog\x18\x04 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nnneighbors\x18\x05 \x01(\x05H\x01\x88\x01\x01\x42\n\n\x08_catalogB\r\n\x0b_nneighbors\".\n\x12\x43onesearchResponse\x12\x18\n\x07objects\x18\x01 \x03(\x0b\x32\x07.Object\"P\n\x06Object\x12\n\n\x02ra\x18\x01 \x01(\x02\x12\x0b\n\x03\x64\x65\x63\x18\x02 \x01(\x02\x12\n\n\x02id\x18\x03 \x01(\t\x12\x10\n\x08\x64istance\x18\x04 \x01(\x02\x12\x0f\n\x07\x63\x61talog\x18\x05 \x01(\t2H\n\rXmatchService\x12\x37\n\nConesearch\x12\x12.ConesearchRequest\x1a\x13.ConesearchResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_server.xmatch_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_CONESEARCHREQUEST']._serialized_start=29
  _globals['_CONESEARCHREQUEST']._serialized_end=163
  _globals['_CONESEARCHRESPONSE']._serialized_start=165
  _globals['_CONESEARCHRESPONSE']._serialized_end=211
  _globals['_OBJECT']._serialized_start=213
  _globals['_OBJECT']._serialized_end=293
  _globals['_XMATCHSERVICE']._serialized_start=295
  _globals['_XMATCHSERVICE']._serialized_end=367
# @@protoc_insertion_point(module_scope)
