# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from grpc_server import xmatch_pb2 as grpc__server_dot_xmatch__pb2


class XmatchServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Conesearch = channel.unary_unary(
                '/XmatchService/Conesearch',
                request_serializer=grpc__server_dot_xmatch__pb2.ConesearchRequest.SerializeToString,
                response_deserializer=grpc__server_dot_xmatch__pb2.ConesearchResponse.FromString,
                )


class XmatchServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Conesearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_XmatchServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Conesearch': grpc.unary_unary_rpc_method_handler(
                    servicer.Conesearch,
                    request_deserializer=grpc__server_dot_xmatch__pb2.ConesearchRequest.FromString,
                    response_serializer=grpc__server_dot_xmatch__pb2.ConesearchResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'XmatchService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class XmatchService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Conesearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/XmatchService/Conesearch',
            grpc__server_dot_xmatch__pb2.ConesearchRequest.SerializeToString,
            grpc__server_dot_xmatch__pb2.ConesearchResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
