services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile-psql
    environment:
      POSTGRES_DB: multistream
      POSTGRES_USER: alerce
      POSTGRES_PASSWORD: alerce
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
