# Default values for step_starter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: <CHARTNAME>

image:
  repository: ghcr.io/alercebroker/<CHARTNAME>
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets:
  - name: "image-pull-access"
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

service:
  type: ClusterIP
  port: 8000

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
          - matchExpressions:
            - key: eks.amazonaws.com/nodegroup
              operator: In
              ## Override this value with the NodeGroup tag accordingly
              values: []

configmap:
  consumerTopics: ""
  publicServer: ""
  internalServer: ""
  scribeTopic: ""
  metricsTopic: ""
  producerTopic: ""

secrets:
  kafkaAuth:
    enabled: false
    username: ""
    password: ""

imageCredentials:
  registry: ""
  username: ""
  password: ""
  email: ""