version: "3"
services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    env_file:
      - .env
    environment:
      - APP_WORKERS=1
      - APP_THREADS=1
      - prometheus_multiproc_dir=/tmp
      - LOG_LEVEL=INFO
    ports:
    - 5000:5000
