apiVersion: v1
kind: Secret
metadata:
  name: image-pull-access
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
---
{{- range $name, $secret := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
{{- if $secret.immutable }}
immutable: true
{{- end }}
type: {{ $secret.type | default "Opaque" }}
stringData:
{{- range $key, $value := $secret.data }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
