name: build_staging_image
on:
  pull_request:
    branches:
      - main

jobs:
  push_image:
    name: Build image and push to GHCR
    runs-on: ubuntu-latest
    uses: ./.github/workflows/build.yml
    with:
      release_type: rc
