name: build_production_image
on:
  release:
    types:
      - published
      - edited

jobs:
  get_tag:
    name: Prepare tags
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.prep.outputs.tags }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/alercebroker/alerts_api
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [[ $VERSION =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:latest"
          fi
          echo ::set-output name=tags::${TAGS}

  push_image:
    name: Build image and push to GHCR
    runs-on: ubuntu-latest
    needs: get_tag
    steps:
      - name: Build and push
        uses: ./.github/workflows/build.yml
        with:
          tag: ${{needs.get_tag.outputs.tags}}
