name: Build Staging

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_versions:
    uses: ./.github/workflows/update-versions.yaml
    with:
      build-type: production

  lightcurve:
    uses: ./.github/workflows/build.yml
    needs: update_versions
    with:
      build-type: production
      service-name: lightcurve
      base-folder: lightcurve
      build-context: lightcurve
