name: build_production_image
on:
  release:
    types:
      - published
      - edited

jobs:
  push_image:
    name: Build image and push to GHCR
    runs-on: ubuntu-latest
    uses: ./.github/workflows/build.yml
    with:
      release_type: latest
