name: Build Staging

on:
  push:
    branches:
      - main

jobs:
  update_versions:
    uses: ./.github/workflows/update-versions.yaml
    with:
      build-type: staging

  lightcurve:
    uses: ./.github/workflows/build.yml
    needs: update_versions
    with:
      build-type: staging
      service-name: lightcurve
      base-folder: lightcurve
      build-context: lightcurve
