name: CD Astroobject

on:
  push:
    branches:
      - main
    paths:
      - 'astroobject/**'
      - '!astroobject/README.md'

jobs:
  cd_astroobject:
    uses: ./.github/workflows/cd-template.yml
    with:
      packages: 'astroobject' # comma separated list of packages
    secrets:
      ADMIN_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
      AWS_ROLE_STAGING: '${{ secrets.AWS_ROLE_STAGING }}'
