name: CD Lightcurve

on:
  push:
    branches:
      - main
    paths:
      - 'lightcurve/**'
      - '!lightcurve/README.md'
      - 'charts/lightcurve/**'

jobs:
  cd_lightcurve:
    uses: ./.github/workflows/cd-template.yaml
    with:
      packages: 'lightcurve' # comma separated list of packages
      event: ${{ github.event_name }} 
    secrets:
      ADMIN_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
      AWS_ROLE_STAGING: '${{ secrets.AWS_ROLE_STAGING }}'
      AWS_ROLE_PRODUCTION: '${{ secrets.AWS_ROLE_PRODUCTION }}'
