name: CD Lightcurve

on:
  push:
    branches:
      - main
    paths:
      - 'lightcurve/**'
      - '!lightcurve/README.md'
      - 'charts/lightcurve/**'

jobs:
  cd_lightcurve:
    uses: ./.github/workflows/cd-template.yml
    with:
      packages: 'lightcurve' # comma separated list of packages
      event: ${{ github.event_name }} 
    secrets:
      ADMIN_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
      AWS_ROLE_STAGING: '${{ secrets.AWS_ROLE_STAGING }}'
      AWS_ROLE_PRODUCTION: '${{ secrets.AWS_ROLE_PRODUCTION }}'
  
  deploy_magstats:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_STAGING }}
          aws-region: us-east-1
          output-credentials: true
          unset-current-credentials: true
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install dependencies
        run: |
          cd ci
          poetry install
      - name: Run dagger pipeline
        run: |
          cd ci
          poetry run python main.py deploy magstats staging

  deploy_object_details:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main
      - name: Configure AWS credentials
        id: creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_STAGING }}
          aws-region: us-east-1
          output-credentials: true
          unset-current-credentials: true
      - name: Install poetry
        run: pipx install poetry
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: 'poetry'
      - name: Install dependencies
        run: |
          cd ci
          poetry install
      - name: Run dagger pipeline
        run: |
          cd ci
          poetry run python main.py deploy object-details staging
