name: CD Lightcurve

on:
  push:
    branches:
      - main
    paths:
      - 'xmatch-service/**'
      - '!xmatch-service/README.md'
      - 'charts/xmatch-service/**'

jobs:
  cd_xmatch:
    uses: ./.github/workflows/cd-template.yml
    with:
      packages: 'xmatch-service' # comma separated list of packages
      event: ${{ github.event_name }} 
    secrets:
      ADMIN_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
      AWS_ROLE_STAGING: '${{ secrets.AWS_ROLE_STAGING }}'
      AWS_ROLE_PRODUCTION: '${{ secrets.AWS_ROLE_PRODUCTION }}'
