name: Lint multisurvey
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - "multisurveys-apis/**"
      - "!multisurveys-apis/README.md"
      - "!multisurveys-apis/.gitignore"

jobs:
  run_ruff:
    format:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Lint with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "format --check --diff"
    lint:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Lint with ruff
        uses: astral-sh/ruff-action@v3
        with:
          args: "check --check --diff --output=github"
