name: Lint with Poetry

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.11'
      poetry-version:
        required: false
        type: string
        default: '1.5.1'
      base-folder:
        required: false
        type: string
        default: '.'
      poetry-install:
        required: false
        type: string
        default: "--all-extras"
    secrets:
      GH_TOKEN:
        required: false

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      POETRY_HOME: /opt/poetry
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_TOKEN}}
          submodules: 'recursive'
      - name: Install poetry
        run: pipx install poetry==${{ inputs.poetry-version }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'poetry'
      - name: Install dependencies
        run: |
          cd ${{ inputs.base-folder }}
          git config --global url."https://${{secrets.GH_TOKEN}}@github.com/".insteadOf "https://github.com/"
          poetry install ${{ inputs.poetry-install }}
      - name: Run Ruff formatter
        run: ruff format --diff
      - name: Run Ruff lint
        run: ruff check --diff
