name: Tests lightcurve
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - 'lightcurve/**'
      - '!lightcurve/README.md'

jobs:
  lightcurve_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test unit lightcurve
        uses: ./.github/workflows/test_template.yaml
        with:
            python-version: '3.11'
            sources-folder: 'src'
            test-folder: 'tests'
            base-folder: 'lightcurve'
        secrets:
          GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

---
name: Tests astroobject
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - 'astroobject/**'
      - '!astroobject/README.md'

jobs:
  astroobject_unittests:
    runs-on: ubuntu-latest
    steps:
      - name: Test unit astroobject
        uses: ./.github/workflows/test_template.yaml
        with:
            python-version: '3.11'
            sources-folder: 'astroobject'
            test-folder: 'tests/unittests'
            base-folder: 'astroobject'
        secrets:
          GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
  astroobject_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test integration astroobject
        uses: ./.github/workflows/test_template.yaml
        with:
            python-version: '3.11'
            sources-folder: 'astroobject'
            test-folder: 'tests/integration'
            base-folder: 'astroobject'
            codecov-flags: ""
        secrets:
          GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

---
name: Tests xmatch
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - 'xmatch-service/**'
      - '!xmatch-service/README.md'
      - 'charts/xmatch-service/**'

jobs:
  xmatch_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test xmatch
        uses: ./.github/workflows/test_template.yaml
        with:
          python-version: '3.11'
          sources-folder: 'src'
          test-folder: 'tests'
          base-folder: 'xmatch-service'
        secrets:
          GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

---
name: Test multisurvey object
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - "multisurveys-apis/pyproject.toml"
      - "multisurveys-apis/poetry.lock"
      - "multisurveys-apis/src/core/**"
      - "multisurveys-apis/src/object_api/**"
      - "multisurveys-apis/tests/core/**"
      - "multisurveys-apis/tests/object_api/**"

jobs:
  ms_object_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test multisutvey object
        uses: ./.github/workflows/test_template.yaml
        with:
          python-version: '3.11'
          sources-folder: 'src'
          test-folder: 'tests/object_api'
          base-folder: 'multisurveys-apis'
        secrets:
          GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'

---
name: Test multisurvey test
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - "multisurveys-apis/pyproject.toml"
      - "multisurveys-apis/poetry.lock"
      - "multisurveys-apis/src/core/**"
      - "multisurveys-apis/src/tests_api/**"
      - "multisurveys-apis/tests/core/**"
      - "multisurveys-apis/tests/tests_api/**"

jobs:
  ms_object_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Test multisutvey test
        uses: ./.github/workflows/test_template.yaml
        with:
          python-version: '3.11'
          sources-folder: 'src'
          test-folder: 'tests/test_api'
          base-folder: 'multisurveys-apis'
        secrets:
          GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
---
name: Test build multisurvey
on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - "multisurveys-apis/**"
      - "!multisurveys-apis/README.md"
      - "!multisurveys-apis/.gitignore"

jobs:
  ms_test_build:
    runs-on: ubuntu-latest
    steps:
      - name: build
        uses: ./.github/workflows/build_template_ms.yaml
        with:
          packages: 'multisurveys-apis'
          build_flags: '--dry-run'
        secrets:
          GH_TOKEN: '${{ secrets.ADMIN_TOKEN }}'
